spring:
  profiles:
    active: development
---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    client-service: /clients/**
    product-service: /products/**
    crm-service: /crm/**
    dashboard-service: /dashboard/**
    contrat-service: /contrat/**
    borj-dashboard: /borj/dashboard/**
    borj-vente: /borj/vente/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: default
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    client-service: /clients/**
    product-service: /products/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/