spring:
  profiles: default
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  routes:
    microservice-1:
      path: /service1/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/